name: Release

on:
  workflow_dispatch:
    inputs:
      build-binary:
        description: 'Build Binary'
        required: false
        type: boolean
        default: true

jobs:

  build-binary:
    name: Build binary
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Prepare output filename
        run: |
          OUTPUT_FILENAME="glibc-tests.tar.gz"
          echo "OUTPUT_FILENAME=$OUTPUT_FILENAME" >> $GITHUB_ENV
          echo "Filename: ${OUTPUT_FILENAME}"

      - name: Check version
        run: ldd --version

      - name: Build binary
        run: cargo build --release

      - name: Prepare artifacts
        run: |
          mkdir -p artifacts
          tar -czf "artifacts/${OUTPUT_FILENAME}" -C target/release glibc-tests

      - name: Upload artifacts
        uses: actions/upload-artifact@v4.3.1
        with:
          name: ${{ env.OUTPUT_FILENAME }}
          path: artifacts/${{ env.OUTPUT_FILENAME }}

